'''network builder for event-related tweets
using format provided by Chris Cassa and Megan Williams'''
import string

class NetworkBuilder(object):
    def __init__(self, network_hash, network_name):
        self.network_hash = network_hash
        self.network_name = network_name
        
    def store_network_hash_as_edgefile(self):
        #takes a network hash generated by tweet_parser and stores as edge file
        edge_file = open('%s_edge_file.csv' %(self.network_name),'w')
        edge_file.write("source,target,timestamp,text,edge_type")
        for e_source in self.network_hash:
            for e_target in self.network_hash[e_source]:
                for e_obj in self.network_hash[e_source][e_target]:
                    clean_text = string.replace(e_obj[1],",","")
                    edge_file.write("%s,%s,%s,%s,%s\n" %(e_source, e_target, e_obj[2], e_obj[1], e_obj[0]))
        
        